CREATE SERVER oracle
FOREIGN DATA WRAPPER ansilo_fdw 
OPTIONS (
    data_source 'oracle'
);

IMPORT FOREIGN SCHEMA "*" 
LIMIT TO ("SYS.DUAL")
FROM SERVER oracle INTO public;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ansiloapp;
