name: Ansilo

networking:
  port: 0 # use kernel-allocated port

auth:
  users:
    - username: app
      password: pass

sources:
  - id: mysql
    type: jdbc.mysql
    options:
      jdbc_url: jdbc:mysql://${env:MYSQL_IP}:3307/db
      properties:
        user: ansilo_admin
        password: ansilo_testing

build:
  stages:
    - sql: ${dir}/ansilo-mysql-sql/*.sql

postgres:
    install_dir: ${env:ANSILO_TEST_PG_DIR:/usr/lib/postgresql/15/}
    data_dir: ${env:TEMP_DIR}/data
    listen_socket_dir_path: ${env:TEMP_DIR}
    fdw_socket_path: ${env:TEMP_DIR}/fdw.sock
    build_info_path: ${env:TEMP_DIR}/build-info.json