name: Ansilo

networking:
  port: 0 # use kernel-allocated port

auth:
  users:
    - username: app
      password: pass

sources:
  - id: oracle
    type: jdbc.oracle
    options:
      jdbc_url: jdbc:oracle:thin:@${env:ORACLE_IP}:1522/db
      properties:
        oracle.jdbc.user: ansilo_admin
        oracle.jdbc.password: ansilo_testing

  - id: mysql
    type: peer
    options:
      url: ${env:URL_MYSQL}
      username: app
      password: pass

build:
  stages:
    - sql: ${dir}/ansilo-oracle-sql/*.sql

postgres:
    install_dir: ${env:ANSILO_TEST_PG_DIR:/usr/lib/postgresql/15/}
    data_dir: ${env:TEMP_DIR}/data
    listen_socket_dir_path: ${env:TEMP_DIR}
    fdw_socket_path: ${env:TEMP_DIR}/fdw.sock
    build_info_path: ${env:TEMP_DIR}/build-info.json