CREATE USER ansilo_admin WITH PASSWORD 'ansilo_testing';
GRANT ALL PRIVILEGES ON DATABASE postgres TO ansilo_admin WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON SCHEMA public TO ansilo_admin WITH GRANT OPTION;