BEGIN
EXECUTE IMMEDIATE 'DROP TABLE T005__TEST_TAB';
EXCEPTION
WHEN OTHERS THEN NULL;
END;
$$

CREATE TABLE T005__TEST_TAB (
    COL VARCHAR2(255)
)
$$

INSERT INTO T005__TEST_TAB (COL) VALUES ('FOO')
$$

INSERT INTO T005__TEST_TAB (COL) VALUES ('BAR')
