BEGIN
EXECUTE IMMEDIATE 'DROP TABLE T007__TEST_TAB';
EXCEPTION
WHEN OTHERS THEN NULL;
END;
$$

CREATE TABLE T007__TEST_TAB (
    ID INT,
    NAME VARCHAR2(255)
)
$$

INSERT ALL
    INTO T007__TEST_TAB (ID, NAME) VALUES (1, 'John')
    INTO T007__TEST_TAB (ID, NAME) VALUES (2, 'Jane')
    INTO T007__TEST_TAB (ID, NAME) VALUES (3, 'Mary')
SELECT 1 FROM DUAL