[workspace]
members = [
    "ansilo-main",
    "ansilo-pgx",
    "ansilo-pg",
    "ansilo-core",
    "ansilo-config",
    "ansilo-secrets",
    "ansilo-auth",
    "ansilo-proxy",
    "ansilo-catalog",
    "ansilo-jobs",
    "ansilo-connectors/*",
    "ansilo-workbench",
    "ansilo-deploy",
    "ansilo-logging",
    "ansilo-util/*",
    "ansilo-e2e",
]
