[workspace]
members = [
    "ansilo-main",
    "ansilo-pgx",
    "ansilo-pg",
    "ansilo-core",
    "ansilo-config",
    "ansilo-secrets",
    "ansilo-auth",
    "ansilo-catalog",
    "ansilo-jobs",
    "ansilo-connectors",
    "ansilo-workbench",
    "ansilo-deploy",
    "ansilo-logging",
]
