[package]
name = "ansilo-config"
version = "0.1.0"
edition = "2021"

[dependencies]
ansilo-core = { path = "../ansilo-core" }
ansilo-logging = { path = "../ansilo-logging" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
