BEGIN
EXECUTE IMMEDIATE 'DROP TABLE T009__TEST_SOURCE';
EXCEPTION
WHEN OTHERS THEN NULL;
END;
$$
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE T009__TEST_TARGET';
EXCEPTION
WHEN OTHERS THEN NULL;
END;
$$

CREATE TABLE T009__TEST_SOURCE (
    ID INT,
    NAME VARCHAR2(255)
)
$$

CREATE TABLE T009__TEST_TARGET (
    ID INT,
    NAME VARCHAR2(255),
    SOURCE VARCHAR2(255),
    CREATED_AT TIMESTAMP WITH TIME ZONE
)
$$

INSERT ALL
    INTO T009__TEST_SOURCE (ID, NAME) VALUES (1, 'John')
    INTO T009__TEST_SOURCE (ID, NAME) VALUES (2, 'Emma')
    INTO T009__TEST_SOURCE (ID, NAME) VALUES (3, 'Jane')
SELECT 1 FROM DUAL
