[package]
name = "ansilo-pg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansilo-connectors = { version = "0.1.0", path = "../ansilo-connectors" }
ansilo-core = { version = "0.1.0", path = "../ansilo-core" }
ansilo-logging = { version = "0.1.0", path = "../ansilo-logging" }
bincode = { version = "2.0.0-rc.1", features = ["serde"] }
nix = "0.24"
postgres = "0.19"
r2d2_postgres = "0.18"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
