[package]
name = "ansilo-pg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansilo-core = { version = "0.1.0", path = "../ansilo-core" }
ansilo-logging = { version = "0.1.0", path = "../ansilo-logging" }
nix = "0.24.1"
postgres = "0.19"
r2d2_postgres = "0.18"
