[package]
name = "ansilo-util-url"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansilo-core = { path = "../../ansilo-core" }
reqwest = { version = "0.11", features = ["native-tls", "blocking"] }
