BEGIN
EXECUTE IMMEDIATE 'DROP TABLE T010__TEST_TAB';
EXCEPTION
WHEN OTHERS THEN NULL;
END;
$$

CREATE TABLE T010__TEST_TAB (
    ID INT,
    NAME VARCHAR2(255),
    COUNTRY CHAR(2 CHAR)
)
$$

INSERT ALL
    INTO T010__TEST_TAB (ID, NAME, COUNTRY) VALUES (1, 'John', 'AU')
    INTO T010__TEST_TAB (ID, NAME, COUNTRY) VALUES (2, 'Mary', 'NZ')
    INTO T010__TEST_TAB (ID, NAME, COUNTRY) VALUES (3, 'Jane', 'US')
    INTO T010__TEST_TAB (ID, NAME, COUNTRY) VALUES (4, 'Sam', 'AU')
    INTO T010__TEST_TAB (ID, NAME, COUNTRY) VALUES (5, 'Tom', 'NZ')
    INTO T010__TEST_TAB (ID, NAME, COUNTRY) VALUES (6, 'Will', 'AU')
SELECT 1 FROM DUAL