BEGIN
EXECUTE IMMEDIATE 'DROP TABLE B001__TEST_TAB';
EXCEPTION
WHEN OTHERS THEN NULL;
END;
$$

CREATE TABLE B001__TEST_TAB (
    X NUMBER
)
$$

INSERT INTO B001__TEST_TAB
    SELECT LEVEL n
    FROM DUAL
    CONNECT BY LEVEL <= 100000
    