name: Customers

networking:
  port: 5003

auth:
  providers:
    - id: jwt
      type: jwt
      jwk: https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_w97qYETe0/.well-known/jwks.json
      login:
        type: oauth2
        authorize_endpoint: https://test-ansilo-demo.auth.ap-southeast-2.amazoncognito.com/login
        params:
          client_id: 21iais50jj7blc3rkr6paqbrqd
          redirect_uri: ${origin}
          response_type: token

  users:
    - username: app
      password: pass
      description: Standard app user

    - username: token
      provider: jwt
      description: Coginto token user

  service_users:
    - username: app
      description: Test
      password: pass

jobs:
  - id: cron_job
    service_user_id: svc
    triggers:
      - cron: "0 0 0 * * *"
    sql: |
      UPDATE jobs 
      SET 
        runs = runs + 1, 
        usr = current_user


build:
  stages:
    - sql: ${dir}/ansilo/*.sql

postgres:
    data_dir: /tmp/${dir}/data
    listen_socket_dir_path: /tmp/${dir}
    fdw_socket_path: /tmp/${dir}/fdw.sock
    build_info_path: /tmp/${dir}/build-info.json