IMPORT FOREIGN SCHEMA "ANSILO_ADMIN.B001__%" 
FROM SERVER oracle INTO public;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app;

CREATE SCHEMA peer;

IMPORT FOREIGN SCHEMA "%" 
FROM SERVER mysql INTO peer;

GRANT USAGE ON SCHEMA peer TO app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA peer TO app;
