BEGIN
EXECUTE IMMEDIATE 'DROP TABLE T013__PEOPLE';
EXCEPTION
WHEN OTHERS THEN NULL;
END;
$$

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE T013__PETS';
EXCEPTION
WHEN OTHERS THEN NULL;
END;
$$

CREATE TABLE T013__PEOPLE (
    ID INT,
    NAME VARCHAR2(255)
)
$$

CREATE TABLE T013__PETS (
    ID INT,
    NAME VARCHAR2(255),
    OWNER_ID INT
)
$$

INSERT ALL
    INTO T013__PEOPLE (ID, NAME) VALUES (1, 'John')
    INTO T013__PEOPLE (ID, NAME) VALUES (2, 'Mary')
    INTO T013__PEOPLE (ID, NAME) VALUES (3, 'Jane')

    INTO T013__PETS (ID, NAME, OWNER_ID) VALUES (1, 'Luna', 1)
    INTO T013__PETS (ID, NAME, OWNER_ID) VALUES (2, 'Salt', 1)
    INTO T013__PETS (ID, NAME, OWNER_ID) VALUES (3, 'Pepper', 3)
    INTO T013__PETS (ID, NAME, OWNER_ID) VALUES (4, 'Morris', NULL)
SELECT 1 FROM DUAL