BEGIN
EXECUTE IMMEDIATE 'DROP TABLE T003__TEST_TAB';
EXCEPTION
WHEN OTHERS THEN NULL;
END;
$$

CREATE TABLE T003__TEST_TAB (
    COL_CHAR CHAR(1 CHAR),
    COL_NCHAR NCHAR(2),
    COL_VARCHAR2 VARCHAR2(255),
    COL_NVARCHAR2 NVARCHAR2(255),
    COL_NUMBER NUMBER,
    COL_FLOAT FLOAT,
    COL_BINARY_FLOAT BINARY_FLOAT,
    COL_BINARY_DOUBLE BINARY_DOUBLE,
    COL_RAW RAW(255),
    COL_LONG_RAW LONG RAW,
    COL_BLOB BLOB,
    COL_CLOB CLOB,
    COL_NCLOB NCLOB,
    COL_JSON JSON,
    COL_DATE DATE,
    COL_TIMESTAMP TIMESTAMP,
    COL_TIMESTAMP_TZ TIMESTAMP WITH TIME ZONE,
    COL_TIMESTAMP_LTZ TIMESTAMP WITH LOCAL TIME ZONE,
    COL_NULL CHAR
)
