BEGIN
EXECUTE IMMEDIATE 'DROP TABLE T002__TEST_TAB';
EXCEPTION
WHEN OTHERS THEN NULL;
END;
$$

CREATE TABLE T002__TEST_TAB (
    COL_CHAR CHAR(5),
    COL_NCHAR NCHAR(5),
    COL_VARCHAR2 VARCHAR2(255),
    COL_NVARCHAR2 NVARCHAR2(255),
    COL_NUMBER NUMBER,
    COL_FLOAT FLOAT,
    COL_BINARY_FLOAT BINARY_FLOAT,
    COL_BINARY_DOUBLE BINARY_DOUBLE,
    COL_RAW RAW(255),
    COL_LONG_RAW LONG RAW,
    COL_BLOB BLOB,
    COL_CLOB CLOB,
    COL_NCLOB NCLOB,
    COL_JSON JSON,
    COL_DATE DATE,
    COL_TIMESTAMP TIMESTAMP,
    COL_TIMESTAMP_TZ TIMESTAMP WITH TIME ZONE,
    COL_TIMESTAMP_LTZ TIMESTAMP WITH LOCAL TIME ZONE,
    COL_NULL CHAR
)
$$

INSERT INTO T002__TEST_TAB (
    COL_CHAR,
    COL_NCHAR,
    COL_VARCHAR2,
    COL_NVARCHAR2,
    COL_NUMBER,
    COL_FLOAT,
    COL_BINARY_FLOAT,
    COL_BINARY_DOUBLE,
    COL_RAW,
    COL_LONG_RAW,
    COL_BLOB,
    COL_CLOB,
    COL_NCLOB,
    COL_JSON,
    COL_DATE,
    COL_TIMESTAMP,
    COL_TIMESTAMP_TZ,
    COL_TIMESTAMP_LTZ,
    COL_NULL
) VALUES (
    'A',
    '🔥',
    'foobar',
    '🥑🚀',
    123.456,
    567.89,
    11.22,
    33.44,
    UTL_RAW.CAST_TO_RAW('RAW'),
    UTL_RAW.CAST_TO_RAW('LONG RAW'),
    UTL_RAW.CAST_TO_RAW('BLOB'),
    'CLOB',
    'NCLOB',
    '{"foo": "bar"}',
    DATE '2020-12-23',
    TIMESTAMP '2018-02-01 01:02:03',
    TIMESTAMP '1999-01-15 11:00:00 -5:00',
    TIMESTAMP '1997-01-31 09:26:56.66 +02:00',
    NULL
)