BEGIN
EXECUTE IMMEDIATE 'DROP TABLE T019__NO_SUPPORTED_COLS';
EXCEPTION
WHEN OTHERS THEN NULL;
END;
$$
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE T019__ONE_SUPPORTED_COLS';
EXCEPTION
WHEN OTHERS THEN NULL;
END;
$$

CREATE TABLE T019__NO_SUPPORTED_COLS (
    xml XMLType
)
$$

CREATE TABLE T019__ONE_SUPPORTED_COLS (
    str VARCHAR2(255),
    xml XMLType
)