CREATE SERVER mysql
FOREIGN DATA WRAPPER ansilo_fdw 
OPTIONS (
    data_source 'mysql'
);

IMPORT FOREIGN SCHEMA "db.t006__%" 
FROM SERVER mysql INTO public;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app;
