BEGIN
EXECUTE IMMEDIATE 'DROP TABLE T006__TEST_TAB';
EXCEPTION
WHEN OTHERS THEN NULL;
END;
$$

CREATE TABLE T006__TEST_TAB (
    NAME VARCHAR2(255)
)
$$

INSERT ALL
    INTO T006__TEST_TAB (NAME) VALUES ('John')
    INTO T006__TEST_TAB (NAME) VALUES ('Mary')
    INTO T006__TEST_TAB (NAME) VALUES ('Jane')
SELECT 1 FROM DUAL