# name: Build

# on:
#   push:
#     branches:
#       - master
#       - develop
#   pull_request:
#     branches:
#       - master
#       - develop

# env:
#   AWS_DEFAULT_REGION: ap-southeast-2

# jobs:
#   build:
#     name: build
#     runs-on: ${{ matrix.os }}
#     if: "!contains(github.event.head_commit.message, 'nogha')"

#     strategy:
#       matrix:
#         os: ["ubuntu-20.04"]

#     steps:
#       - uses: actions/checkout@v3

#       - name: Build base image
#         run: |
#           docker build -t ansilo-source \
#             --file .github/workflows/docker/source.ubi9.Dockerfile \
#             .

#       - name: Run release build
#         run: |
#           docker build -t ansilo-release \
#             --file .github/workflows/docker/release.ubi9.Dockerfile \
#             .

#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
#           aws-region: ap-southeast-2

#       - name: Login to Amazon ECR
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: Push to Amazon ECR
#         env:
#           REGISTRY: 635198228996.dkr.ecr.ap-southeast-2.amazonaws.com
#           REPOSITORY: ansilo-dev
#           IMAGE_TAG: ${{ github.head_ref || github.ref_name }}
#         run: |
#           docker tag ansilo-release $REGISTRY/$REPOSITORY:$IMAGE_TAG
#           docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
