name: Run tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  tests:
    name: tests
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'nogha')"
    env:
      RUSTC_WRAPPER: sccache
      SCCACHE_DIR: /home/runner/.cache/sccache

    strategy:
      matrix:
        os: ["ubuntu-20.04"]

    steps:
      - uses: actions/checkout@v3

      - name: Cache cargo registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: tests-cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock', '.github/workflows/tests.yml') }}

      - name: Cache maven registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.m2
          key: tests-maven-${{ runner.os }}-${{ hashFiles('**/pom.xml', '.github/workflows/tests.yml') }}

      - name: Cache criterion directory
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: target/criterion
          key: tests-criterion-${{ runner.os }}

      - name: Build base image
        run: |
        docker build -t ansilo-source \
          --dockerfile .github/workflows/docker/source.ubi9.Dockerfile \
          -v $HOME/.cargo:/home/build/.cargo \
          .

      - name: Pre test setup
        run: .github/workflows/scripts/pre-test.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TESTS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TESTS_AWS_SECRET_ACCESS_KEY }}

      - name: Run tests
        run: |
          docker build -t tests \
            --dockerfile .github/workflows/docker/test.ubi9.Dockerfile \
            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            -e AWS_DEFAULT_REGION=ap-southeast-2 \
            -e RUSTFLAGS=-Copt-level=0 \
            -e RUST_BACKTRACE=1 \
            -e CARGO_INCREMENTAL=false \
            -e ANSILO_TESTS_ECS_USE_PUBLIC_IP=true \
            # Cached directories
            -v $HOME/.cargo:/home/build/.cargo \
            -v $HOME/.m2:/home/build/.m2 \
            -v $HOME/target:/build/target \
            .
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TESTS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TESTS_AWS_SECRET_ACCESS_KEY }}

      - name: Post tests cleanup
        if: always()
        run: .github/workflows/scripts/post-test.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TESTS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TESTS_AWS_SECRET_ACCESS_KEY }}
