name: Run tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  AWS_DEFAULT_REGION: ap-southeast-2

jobs:
  tests:
    name: tests
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'nogha')"

    strategy:
      matrix:
        os: ["ubuntu-20.04"]

    steps:
      - uses: actions/checkout@v3
      - name: Pre test setup
        run: .github/workflows/scripts/pre-test.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TESTS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TESTS_AWS_SECRET_ACCESS_KEY }}


      - name: Build base image
        run: |
          docker build -t ansilo-source \
            --file .github/workflows/docker/source.ubi9.Dockerfile \
            .

      - name: Run tests
        run: |
          docker build -t tests \
            --file .github/workflows/docker/test.ubi9.Dockerfile \
            --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            --build-arg AWS_DEFAULT_REGION=ap-southeast-2 \
            --build-arg RUSTFLAGS=-Copt-level=0 \
            --build-arg RUST_BACKTRACE=1 \
            --build-arg CARGO_INCREMENTAL=false \
            --build-arg ANSILO_TESTS_ECS_USE_PUBLIC_IP=true \
            .
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TESTS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TESTS_AWS_SECRET_ACCESS_KEY }}

      - name: Post tests cleanup
        if: always()
        run: .github/workflows/scripts/post-test.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TESTS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TESTS_AWS_SECRET_ACCESS_KEY }}
