name: Run tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  tests:
    name: tests
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'nogha')"

    strategy:
      matrix:
        os: ["ubuntu-20.04"]

    steps:
      - uses: actions/checkout@v3

      - name: Build base image
        run: |
          docker build -t ansilo-source \
            --file .github/workflows/docker/source.ubi9.Dockerfile \
            .

      - name: Pre test setup
        run: .github/workflows/scripts/pre-test.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TESTS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TESTS_AWS_SECRET_ACCESS_KEY }}

      - name: Run tests
        run: |
          docker build -t tests \
            --file .github/workflows/docker/test.ubi9.Dockerfile \
            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            -e AWS_DEFAULT_REGION=ap-southeast-2 \
            -e RUSTFLAGS=-Copt-level=0 \
            -e RUST_BACKTRACE=1 \
            -e CARGO_INCREMENTAL=false \
            -e ANSILO_TESTS_ECS_USE_PUBLIC_IP=true \
            .
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TESTS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TESTS_AWS_SECRET_ACCESS_KEY }}

      - name: Post tests cleanup
        if: always()
        run: .github/workflows/scripts/post-test.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TESTS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TESTS_AWS_SECRET_ACCESS_KEY }}
