name: Run tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  AWS_DEFAULT_REGION: ap-southeast-2

jobs:
  tests:
    name: tests
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'nogha')"

    strategy:
      matrix:
        os: ["ubuntu-20.04"]

    steps:
      - uses: actions/checkout@v3

      - name: Cache build image
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: /home/runner/image-build.tgz
          key: ansilo-test-${{ runner.os }}-${{ hashFiles('.github/workflows/docker/build.ubi9.Dockerfile') }}

      - name: Cache cargo/maven registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.m2
            ~/.cargo/registry
            ~/.cargo/git
          key: ansilo-test-cargo-${{ runner.os }}

      - name: Cache target dir
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: target/
          key: ansilo-tests-${{ runner.os }}

      - name: Build base image
        run: .github/workflows/scripts/build-build-image.sh

      - name: Create volume dirs
        run: .github/workflows/scripts/volumes.sh

      - name: Cargo build
        run: |
          docker run \
            -v $HOME/.cargo:/home/build/.cargo \
            -v $HOME/.m2:/home/build/.m2 \
            -v $PWD:/build/ \
            -w /build/ \
            ansilo-build /build/.github/workflows/scripts/test-build.sh

      - name: Test setup
        run: |
          docker run \
            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            -v $HOME/.cargo:/home/build/.cargo \
            -v $HOME/.m2:/home/build/.m2 \
            -v $PWD:/build/ \
            -w /build/ \
            ansilo-build /build/.github/workflows/scripts/test-setup.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TESTS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TESTS_AWS_SECRET_ACCESS_KEY }}

      # - name: Run tests
      #   run: |
      #     docker run \
      #       -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
      #       -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
      #       -v $HOME/.cargo:/home/build/.cargo \
      #       -v $HOME/.m2:/home/build/.m2 \
      #       -v $PWD:/build/ \
      #       -w /build/ \
      #       ansilo-build /build/.github/workflows/scripts/test.sh
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.TESTS_AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.TESTS_AWS_SECRET_ACCESS_KEY }}

      - name: Post tests teardown
        if: always()
        run: |
          docker run \
            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            -v $HOME/.cargo:/home/build/.cargo \
            -v $HOME/.m2:/home/build/.m2 \
            -v $PWD:/build/ \
            -w /build/ \
            ansilo-build /build/.github/workflows/scripts/test-teardown.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TESTS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TESTS_AWS_SECRET_ACCESS_KEY }}
