name: Run tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  RUSTFLAGS: -Copt-level=0
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: "false"
  AWS_DEFAULT_REGION: ap-southeast-2

jobs:
  tests:
    name: tests
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'nogha')"
    env:
      RUSTC_WRAPPER: sccache
      SCCACHE_DIR: /home/runner/.cache/sccache

    strategy:
      matrix:
        version: ["postgres-14"]
        os: ["ubuntu-20.04"]

    steps:
    - uses: actions/checkout@v3

    - name: Cache cargo registry
      uses: actions/cache@v2
      continue-on-error: false
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: tests-cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock', '.github/workflows/tests.yml') }}

    - name: Cache maven registry
      uses: actions/cache@v2
      continue-on-error: false
      with:
        path: |
          ~/.m2
        key: tests-maven-${{ runner.os }}-${{ hashFiles('**/pom.xml', '.github/workflows/tests.yml') }}

    - name: Cache sccache directory
      uses: actions/cache@v2
      continue-on-error: false
      with:
        path: /home/runner/.cache/sccache
        key: tests-sccache-${{ runner.os }}-${{ hashFiles('**/Cargo.lock', '.github/workflows/tests.yml') }}

    - name: Set up prerequisites and environment
      run: .github/workflows/scripts/setup.sh
      env:
        POSTGRES_VERSION: ${{ matrix.version }}

    - name: Run tests
      run: |
        .github/workflows/scripts/pre-build.sh
        cargo test
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.TESTS_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.TESTS_AWS_SECRET_ACCESS_KEY }}

    - name: Run benchmarks
      run: |
        cargo bench
      env:
        RUSTFLAGS: ""
        AWS_ACCESS_KEY_ID: ${{ secrets.TESTS_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.TESTS_AWS_SECRET_ACCESS_KEY }}

    - name: Teardown environment
      run: .github/workflows/scripts/teardown.sh
      env:
        POSTGRES_VERSION: ${{ matrix.version }}

