name: Run tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  AWS_DEFAULT_REGION: ap-southeast-2

jobs:
  tests:
    name: tests
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'nogha')"

    strategy:
      matrix:
        os: ["ubuntu-20.04"]

    steps:
      - uses: actions/checkout@v3

      - name: Cache build image
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: /home/runner/image-build.tgz
          key: ansilo-${{ runner.os }}-${{ hashFiles('.github/workflows/docker/build.ub9.Dockerfile') }}

      - name: Build base image
        run: .github/workflows/scripts/build-build-image.sh

      - name: Pre test setup
        run: .github/workflows/scripts/pre-test.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TESTS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TESTS_AWS_SECRET_ACCESS_KEY }}

      # - name: Run tests
      #   run: |
      #     docker build -t tests \
      #       --file .github/workflows/docker/test.ubi9.Dockerfile \
      #       --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
      #       --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
      #       .
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.TESTS_AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.TESTS_AWS_SECRET_ACCESS_KEY }}

      - name: Post tests cleanup
        if: always()
        run: .github/workflows/scripts/post-test.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TESTS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TESTS_AWS_SECRET_ACCESS_KEY }}
